language: csharp
solution: UlstuScheduleParser.sln
mono: none
dotnet: 2.1.502
install:
 - dotnet tool install coveralls.net --version 1.0.0 --tool-path tools
script:
 - dotnet restore
 - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
 - ls tools
 - ls tools/csmacnz.Coveralls
 - cat tools/csmacnz.Coveralls
 - ./tools/csmacnz.Coveralls --opencover -i ./UlstuScheduleParser.Tests/coverage.opencover.xml --repoTokenVariable repo_token
